user1 = User.create(username: "Franco", password_digest: "Lemontime", email: "Frank@link.com", image: "https://i.ibb.co/WfKY7RT/Screenshot-2020-02-18-at-10-48-08.png", bio: "Originally from London, living in Perth, seasoned surfer/traveller")
user2 = User.create(username: "Pete_swell", password_digest: "surftime", email: "petersmith@gmail.com", image: "https://i.ibb.co/VDDzFnf/Screenshot-2020-02-18-at-10-45-38.png", bio: "I travel far and wide to catc the best breaks, checkout my pics")
user3 = User.create(username: "Marny-fire", password_digest: "password", email: "surflady@pineapple.com", image: "https://i.ibb.co/m5JTW8t/Screenshot-2020-02-18-at-10-42-32.png", bio: "Surf champion UK 2016, and fifth time regional champion in Cornwall")
user4 = User.create(username: "Benji", password_digest: "benji2", email: "benboo@hotmail.com", image: "https://i.ibb.co/QPj64Dy/Screenshot-2020-02-18-at-10-44-44.png", bio: "Advanced, i teach, so holla!")


story1 = Story.create(user_id: user2.id, image: "https://ssl.quiksilver.com/static/QS/default/category-assets/marketing-landing/landing/img/surf/tiles/surf_featured_1.jpg", title: "Left my heart in Lagos", content: "Portugal has sun most of the year, and some of the beaches in and around lagos have the craziest swell. So many spots to choose from. And sick hostels and nightlife.", region: "Lagos", country: "Portugal", latitude: "67", longitude: "98")
story2 = Story.create(user_id: user3.id, image: "https://gttp.imgix.net/199497/x/0/guide-to-surfing-in-siargao-cloud-9-and-other-surf-spots-tips-3.jpg?auto=compress%2Cformat&ch=Width%2CDPR&dpr=1&ixlib=php-2.3.0&w=883", title: "The magic of General Luna", content: "Siargao is my favourite philippino island with a definite surf vibe and surf bum attitude. Theres a party somehwere on the island everynight, and the cloud9 is the place to go for the best breaks. I stayed at Smiling Pig hostel; you can rent a surf instructor from there, or just go down to the boardwalk where instructors are waiting. The island has natural beauty with an abundance of palm trees, and great local bbq. windsurfing at Bravo also.", region: "Siargao", country: "Philippines", latitude: "45", longitude: "46")
story3 = Story.create(user_id: user1.id, image: "https://static.nationalgeographic.co.uk/files/styles/image_1900/public/ngts_gettyimages-932140464.jpg", title: "If you don't know Woolacombe, who even are you?", content: "2 mile strech of sand, dunes and phat breaks, in North Devon. The red barn is a cool surf/pub/bar with live music most evenings. Theres plenty of short-term let holiday apartments to rent (although go for one in the center of the village- right by the beach, or you could be a fair walk up the hill)", region: "Woolacombe", country: "England", latitude: "83", longitude: "99")
story4 = Story.create(user_id: user4.id, image: "https://cdn2.outdoorphotographer.com/2018/01/mclark_fpta_0811_08478.jpg", title: "Croyde regular", content: "Croyde Bay in Devon is picturesque, quiet, not overcrowded, sandy, and the biggest waves youll see on the southwest coastline. If you're looking to get away from families holidaying, or humans, this place is perfect- campervan it!", region: "Croyde Bay", country: "England", latitude: "29", longitude: "39")
story5 = Story.create(user_id: user1.id, image: "https://i.ibb.co/n0NrJkZ/Screenshot-2020-02-18-at-10-47-37.png", title: "Hands up whos a van life nomad??", content: "Have you ever dreamt of leaving it all behind and living the van life?? my advice - DO IT!! honestly we've never looked back. I'm better off financially, and travel and surf are my absolute passions. Whats the point of life if you can't live your dreams. What's stopping you??!", region: "Byron Bay", country: "Australia", latitude: "87", longitude: "96")

favourite1 = Favourite.create(user_id: user1.id, story_id: story4.id)